### ISSUE TITLE
MultiLineRenderer not displaying all lines in certain configurations

### ISSUE THREAD

**Issue by srslylawl** [QThund/LineRenderer2D#3]
Sampling tPackedPoints in S_BresenhamMultiLine.hlsl to get packedPoints/packedPoints2 returns the wrong packed point in a variety of configurations, which causes some lines to not get rendered entirely.

I managed to fix it by replacing the first part of the outer for loop of IsPixelInLine_float with

```
int xCoord = floor(t/2.0f);
float4 packedPoints = tPackedPoints.Load(int3(xCoord, 0, 0));
float4 packedPoints2 = tPackedPoints.Load(int3(xCoord+1, 0, 0));
```

**Comment by QThund** [comment]
Thank you srslylawl, your fix has been reproduced and applied to the repo.
https://github.com/QThund/LineRenderer2D/commit/b506d51e4ea7129cf44ee4ba82efc2ce666db856#diff-f1826078b5cdab5080f9e00e40581c875f28472e5d7a17b475fcfefb0eb941ac
